# Generated by Django 5.2.1 on 2025-09-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter 10 or 11 digits (e.g., 1717508447 or 01717508447)', max_length=14, null=True),
        ),
    ]
