# Generated by Django 5.2.6 on 2025-10-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_address_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the shop assistant', max_length=100)),
                ('contact_number', models.CharField(blank=True, help_text='Contact number in format +8801XXXXXXXXX', max_length=14, null=True)),
                ('joining_date', models.DateField(help_text='Date when the assistant joined')),
                ('assigned_shop', models.CharField(default='Main Branch', help_text='Shop or branch where the assistant works', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the assistant is currently active')),
                ('address', models.TextField(blank=True, help_text='Home address of the assistant', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop Assistant',
                'verbose_name_plural': 'Shop Assistants',
                'ordering': ['name'],
            },
        ),
    ]
