# Generated by Django 5.2.6 on 2025-10-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_shopassistant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopassistant',
            name='assigned_shop',
        ),
    ]
