# Generated by Django 5.2.1 on 2025-09-06 12:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('addition', 'Stock Addition'), ('reduction', 'Stock Reduction'), ('correction', 'Stock Correction')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='inventory.product'),
        ),
    ]
