# Generated by Django 5.2.6 on 2025-10-04 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_shopassistant'),
        ('sales', '0003_alter_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop_assistant',
            field=models.ForeignKey(blank=True, help_text='Shop assistant who helped with this sale', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.shopassistant'),
        ),
    ]
